// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaqxb2i3TGtR5cVjzI3gyQJ-QDGBnZxT0',
    appId: '1:910157469590:web:d95f50663d15945f38efb7',
    messagingSenderId: '910157469590',
    projectId: 'music-matcher-9e5e5',
    authDomain: 'music-matcher-9e5e5.firebaseapp.com',
    storageBucket: 'music-matcher-9e5e5.firebasestorage.app',
    measurementId: 'G-LDXPB3DLWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGO7LjhTpWf0gtgfMT7-DN2zBTI6zZBCs',
    appId: '1:910157469590:android:f45a6a41828883c138efb7',
    messagingSenderId: '910157469590',
    projectId: 'music-matcher-9e5e5',
    storageBucket: 'music-matcher-9e5e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCFw4Ewtns2uhPGwAzFuRCyLLS9qUYAw4',
    appId: '1:910157469590:ios:a0d7f56832c78ba138efb7',
    messagingSenderId: '910157469590',
    projectId: 'music-matcher-9e5e5',
    storageBucket: 'music-matcher-9e5e5.firebasestorage.app',
    iosBundleId: 'com.example.maddata2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCFw4Ewtns2uhPGwAzFuRCyLLS9qUYAw4',
    appId: '1:910157469590:ios:a0d7f56832c78ba138efb7',
    messagingSenderId: '910157469590',
    projectId: 'music-matcher-9e5e5',
    storageBucket: 'music-matcher-9e5e5.firebasestorage.app',
    iosBundleId: 'com.example.maddata2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaqxb2i3TGtR5cVjzI3gyQJ-QDGBnZxT0',
    appId: '1:910157469590:web:ff0ef009e835740438efb7',
    messagingSenderId: '910157469590',
    projectId: 'music-matcher-9e5e5',
    authDomain: 'music-matcher-9e5e5.firebaseapp.com',
    storageBucket: 'music-matcher-9e5e5.firebasestorage.app',
    measurementId: 'G-ND8WZ89BMX',
  );
}
